#!/usr/bin/env python3
"""Build a complete installable app: label + launcher icon, no Android SDK.

This is the first example with a `resources.arsc`. The manifest's
`android:label` and `android:icon` are resource *references* that resolve
through that table: the label to a string, the icon to a packaged PNG. The
icon is generated by the pure-Python encoder in tools/png.py.

The result is an APK that, once installed, appears in the launcher with a name
and an icon — the full shape of a real app, built entirely by hand.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from apkfs import axml
from apkfs import arsc
from apkfs import apk
from apkfs import png
from apkfs import dalvik as dv
from apkfs.dex import DexBuilder, Method

PACKAGE = "com.example.fromscratch"
ACTIVITY = "com.example.fromscratch.Main"
CLASS_DESC = "Lcom/example/fromscratch/Main;"
SUPER_DESC = "Landroid/app/Activity;"

APP_LABEL = "From Scratch"
ICON_PATH = "res/mipmap/ic_launcher.png"
PACKAGE_ID = 0x7F
MESSAGE = "Built by hand: manifest, dex, resources, icon, signature."


def build_dex():
    dx = DexBuilder(CLASS_DESC, SUPER_DESC)
    ctor = dx.methodref(SUPER_DESC, "<init>", "V", [])
    super_oncreate = dx.methodref(SUPER_DESC, "onCreate", "V",
                                  ["Landroid/os/Bundle;"])
    tv_ctor = dx.methodref("Landroid/widget/TextView;", "<init>", "V",
                           ["Landroid/content/Context;"])
    tv_settext = dx.methodref("Landroid/widget/TextView;", "setText", "V",
                              ["Ljava/lang/CharSequence;"])
    set_content = dx.methodref(SUPER_DESC, "setContentView", "V",
                               ["Landroid/view/View;"])
    dx.str(MESSAGE)
    dx.type("Landroid/widget/TextView;")
    dx.add_method(Method("<init>", ("V", []), 0x10001, 1, 1, 1, b""))
    dx.add_method(Method("onCreate", ("V", ["Landroid/os/Bundle;"]),
                         0x1, 6, 2, 2, b""))
    dx.freeze()
    mi = dx.method_index
    msg_idx = dx.string_index(MESSAGE)
    tv_idx = dx.type_index("Landroid/widget/TextView;")
    init = dv.invoke_direct([0], mi(ctor)) + dv.return_void()
    oncreate = (
        dv.invoke_super([4, 5], mi(super_oncreate))
        + dv.new_instance(0, tv_idx)
        + dv.invoke_direct([0, 4], mi(tv_ctor))
        + dv.const_string(1, msg_idx)
        + dv.invoke_virtual([0, 1], mi(tv_settext))
        + dv.invoke_virtual([4, 0], mi(set_content))
        + dv.return_void()
    )
    by_name = {m.name: m for m in dx._defined}
    by_name["<init>"].code = init
    by_name["onCreate"].code = oncreate
    return dx.build()


def build_resources():
    """A resources.arsc with a `string` type (app_name) and a `mipmap` type
    (ic_launcher, whose value is the packaged icon's path)."""
    value_strings = [APP_LABEL, ICON_PATH]
    return arsc.build(PACKAGE_ID, PACKAGE, value_strings, [
        {"name": "string", "keys": ["app_name"],
         "entries": [(0, arsc.TYPE_STRING, 0)]},   # value_strings[0]
        {"name": "mipmap", "keys": ["ic_launcher"],
         "entries": [(0, arsc.TYPE_STRING, 1)]},   # value_strings[1]
    ])


def main():
    label_ref = axml.Ref(arsc.res_id(PACKAGE_ID, 1, 0))   # @string/app_name
    icon_ref = axml.Ref(arsc.res_id(PACKAGE_ID, 2, 0))    # @mipmap/ic_launcher
    manifest = axml.manifest(
        PACKAGE, ACTIVITY, min_sdk=23, target_sdk=28,
        label=label_ref, icon=icon_ref, version_code=1, version_name="1.0")

    files = {
        "AndroidManifest.xml": manifest,
        "classes.dex": build_dex(),
        "resources.arsc": build_resources(),
        ICON_PATH: png.solid_icon(),
    }
    key = apk.make_keypair()
    cert = apk.self_signed_cert(key)
    blob = apk.sign(files, key, cert)
    out = pathlib.Path(__file__).with_name("icon_app.apk")
    out.write_bytes(blob)
    print(f"wrote {out} ({len(blob)} bytes)")
    for name, body in files.items():
        print(f"  {name}: {len(body)} B")


if __name__ == "__main__":
    main()
